### ISSUE TITLE
Doesn't work on BSD

### ISSUE THREAD

**Issue by melody-notpond** [amethyst-lang/amethyst#2]

**Comment by DiamondCoder1000** [comment]
LOL IMAGINE L + BOZO + RATIO + FAHERLESS + TRASH + NO ONE ASKED + DEAD + ORPHAN + HOMELESS + STUPID + L + LOSER + TRASH + BAD + MORON + LOLOL BAD + IDIOT + UR MOM

**Comment by DiamondCoder1000** [comment]
LOL IMAGINE L + BOZO + RATIO + FAHERLESS + TRASH + NO ONE ASKED + DEAD + ORPHAN + HOMELESS + STUPID + L + LOSER + TRASH + BAD + MORON + LOLOL BAD + IDIOT + UR MOM

**Comment by DiamondCoder1000** [comment]
LOL IMAGINE L + BOZO + RATIO + FAHERLESS + TRASH + NO ONE ASKED + DEAD + ORPHAN + HOMELESS + STUPID + L + LOSER + TRASH + BAD + MORON + LOLOL BAD + IDIOT + UR MOM

**Comment by DiamondCoder1000** [comment]
LOL IMAGINE L + BOZO + RATIO + FAHERLESS + TRASH + NO ONE ASKED + DEAD + ORPHAN + HOMELESS + STUPID + L + LOSER + TRASH + BAD + MORON + LOLOL BAD + IDIOT + UR MOM

**Comment by backfromhiatus** [comment]
LOL IMAGINE L + BOZO + RATIO + FAHERLESS + TRASH + NO ONE ASKED + DEAD + ORPHAN + HOMELESS + STUPID + L + LOSER + TRASH + BAD + MORON + LOLOL BAD + IDIOT + UR MOM
